### ISSUE TITLE
关于锚点重加权

### ISSUE THREAD

**Issue by sumingfirst** [lancopku/label-words-are-anchors#20]
首先祝贺大佬论文取得了best paper，大佬不知道你有没有考虑过锚点重加权应用到摘要的方面呢，论文是一个分类的问题，最近也在做相关工作

**Comment by leanwang326** [comment]
没考虑过，主要是摘要偏向生成任务，感觉会有点区别，而且我们毕竟主要focus在interpretation，锚点重加权这个应用做的还是比较粗糙的，我感觉你可以再参考参考In-context Vectors: Making In Context Learning More Effective and Controllable Through Latent Space Steering，他在效果上更好一点

**Comment by sumingfirst** [comment]
你的邮件我受到非常感谢配合

**Comment by sumingfirst** [comment]
多谢大佬啦，大佬回复好用心，希望后面多发大paper哈哈哈哈
