### ISSUE TITLE
关于3.2 Anchor-Only Context Compression的问题

### ISSUE THREAD

**Issue by Cooperx521** [lancopku/label-words-are-anchors#23]
作者您好~
![image](https://github.com/lancopku/label-words-are-anchors/assets/131770126/904e6b67-9302-48a3-9ac3-8ab28b9b0cee)
论文中这一节（如图）提到在每一层之前将label words的hidden state拼接起来，在这里想问一下是在所有的层都这么做还是只在后一半层内这样做，因为正如论文中提到的，在浅层信息聚合，但是如果尚未完成聚合就将其他hidden state删掉，是不是不利于最终的表现。

**Comment by leanwang326** [comment]
是所有层都这么做
浅层聚合是聚合到这些hidden_states上，所以取这些hidden_states就可以了（换个角度，可以认为其他hidden state主要影响这些hidden_state，所以保留这些计算好的hidden_state就涵盖了其他hidden state的大部分影响）

**Comment by leanwang326** [comment]
以及不好意思回复得有点晚了

**Comment by Cooperx521** [comment]
嗯嗯，谢谢您的回复。我看了下代码，似乎是做了两次forward，第一次正常forward，然后利用第一次的kv cache 只留下anchor 进行forward，那这样其实相当于已经获得了聚合后的hidden state，浅层非anchor的token内容已经不重要了，这样的理解正确吗

**Comment by leanwang326** [comment]
是的
