### ISSUE TITLE
How to calculate $I_l(i, j)$

### ISSUE THREAD

**Issue by lucky9-cyou** [lancopku/label-words-are-anchors#24]
Thanks for your wonderful working. I can know how to calculate $I_l$, which is explained in the paper, but it seems that the paper does not explain how to calculate $I_l(i, j)$.

And why $I_l(i, j)$ can represents the significance of the information flow from the j-th word to the i-th word for ICL？

**Comment by leanwang326** [comment]
$I_l(i,j)$ is just the i,j element of I, e.g. $|\frac{\partial Attention_{i,j}}{\partial Loss} * Attention_{i,j}|$

and sorry for the delay. I missed this issue.

**Comment by lucky9-cyou** [comment]
> Il(i,j) is just the i,j element of I, e.g. |∂Attentioni,j∂Loss∗Attentioni,j|
> 
> and sorry for the delay. I missed this issue.

Got it. Thanks for your reply.
