### ISSUE TITLE
请问显著性得分的计算方法为什么是论文中写的那样

### ISSUE THREAD

**Issue by zhangzhen-research** [lancopku/label-words-are-anchors#7]
我对您的文章中提到的显著性得分计算方式有一些困惑。为什么在计算中，左边需要乘以注意力矩阵的转置？右边对注意力矩阵求梯度的部分不就可以直接说明每个注意力参数的显著性了吗。我阅读了您引用的文章，但仍未能解决我的困惑。非常感谢您的回答。

**Comment by leanwang326** [comment]
不好意思，写岔了写岔了，这里该是hardmard积（按位乘），实际就是x*\frac{\partial L}{\partial x}

**Comment by zhangzhen-research** [comment]
非常感谢您的回复，但是我还是有些疑惑，左边的attention矩阵有没有转置，为什么要再左乘attention矩阵呢，单纯对attention矩阵求梯度不就是那个参数的显著性了吗

**Comment by leanwang326** [comment]
谢谢你提出来。至于为啥要多乘一个x是因为这里我们关心的是attention存在与否，所以相当于attention乘以掩码z（z在0-1之间），然后z对于分类loss的梯度，也就是$\frac{\partial L}{\partial z} = \frac{\partial L}{\partial a}\frac{\partial a}{\partial z}=  \frac{\partial L}{\partial a}a	(其中a=a_0 z)$

**Comment by leanwang326** [comment]
类似这篇文章https://arxiv.org/pdf/1905.10650.pdf的4.1节（我公式也是照着他写的，不过它是只要算整个head的重要性而不是某个token_i到token_j的attention的重要性，所以我这应该改成hardmard积）

**Comment by zhangzhen-research** [comment]
感谢！！！！！
